name: Test Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - dev
          - staging
          - prod
        default: dev

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Determine wait time based on selected app.
        id: determine-wait-time
        run: |
          case "${{ inputs.environment }}" in
            "dev") echo "WAIT_TIME=30" >> $GITHUB_ENV ;;
            "staging") echo "WAIT_TIME=60" >> $GITHUB_ENV ;;
            "prod") echo "WAIT_TIME=90" >> $GITHUB_ENV ;;
            *) echo "WAIT_TIME=0" >> $GITHUB_ENV ;;
          esac

      - name: Run tests
        env:
          WAIT_TIME: ${{ steps.determine-wait-time.outputs.WAIT_TIME }}
        run: |
          echo "Wait time: $WAIT_TIME"
          echo "Tests completed"
